# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75f29249c39055e31168e0e5a768f41f603c88068f79170484d350508b0d24cb19f9fbff35e44b276d8c14c6ba83503b99fbd868453164ed5f4f4946472dab53

test:
  secret_key_base: 8ffcb28dd7ce996dcd63795d81ce0d039aec36c199a2aaa7b24f67551138826e73b8fe6f3e515a62a17104186e1092bcc66e290920f7b5159e6220afec339c49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
